name: Deploy Blazor WebAssembly App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./dotnetgirls_site/dotnetgirls_site.csproj

      - name: Build the Blazor WebAssembly app
        run: dotnet publish ./dotnetgirls_site/dotnetgirls_site.csproj --configuration Release --output ./dotnetgirls_site/publish

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dotnetgirls_site/publish/wwwroot'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: main
          folder: './dotnetgirls_site/publish/wwwroot'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
